### ISSUE TITLE
Font issues with search values in dark mode

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#1000]
The headers of the search results don't show up until you hover over it.

Loom video of the behavior [here](https://www.loom.com/share/6aef08dc6fbd4c8688dd2e90913c255e)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_44j024)

**Comment by ashleygmulligan2** [comment]
now fixed
