### ISSUE TITLE
"Adding your first action" grammar fix

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#103]
Currently [this paragraph](https://flatfileinc.mintlify.app/quickstart/submit-action#adding-your-first-action) includes 

> In this example, we're going to add the code the primary action... 

Should be something like

> In this example, we're going to add _to our code_ the primary action... 

Or something similar

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/109
