### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by LeTranAnhVu** [FlatFilers/Guides#1041]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1705497374395779)

Path: /apps/custom/submit-action

This snippet for typescript in https://flatfile.com/docs/apps/custom/submit-action#call-a-webhook is incorrect, I guess.
```
 const { data: workbook } = await api.sheets.list({ workbookId });
```
While on the javascript version is
```
    const { data: workbook } = await api.workbooks.get(workbookId);
```

**Comment by Arsik36** [comment]
Thank you for letting us know, I will consult the team on this :)

**Comment by Arsik36** [comment]
This has been fixed
