### ISSUE TITLE
Issue on docs - no indication how to run anything

### ISSUE THREAD

**Issue by deifante** [FlatFilers/Guides#1045]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1705496026475439)

Path: /apps/custom/meet-the-workbook
no indication how to run anything.

**Comment by Arsik36** [comment]
Thank you for letting us know Deifante, I am passing this to the team
