### ISSUE TITLE
Issue on docs - code in react, not native javascript

### ISSUE THREAD

**Issue by robpearlman** [FlatFilers/Guides#1047]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1705496141266049)

Path: /apps/embedding/javascript/new_space

This code is in react, not native javascript

**Comment by Arsik36** [comment]
Thank you for providing the feedback, passing this to our team for review

**Comment by ashleygmulligan2** [comment]
Hey @robpearlman , I don't see any react on this page: https://flatfile.com/docs/apps/embedding/javascript/new_space - is there perhaps a different page I should be looking at?

**Comment by ashleygmulligan2** [comment]
See it now
