### ISSUE TITLE
Submit Action code missing?

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#107]
Should there be example code for submitting data to webhook.site? I see the example in repl.it under the Actions folder, but it doesn't include a webhook URL, and the example on the page just has a comment, no actual action code. Is the goal here for the developer to build this themselves as they're working through the examples? 

![image](https://user-images.githubusercontent.com/106406547/234099488-af3df3ea-b4ea-46a4-8b5e-984300176d1c.png)

**Comment by ashleygmulligan2** [comment]
I am currently working on this still, hang tight

**Comment by dboskovic** [comment]
This is resolved now
