### ISSUE TITLE
I am stuck

### ISSUE THREAD

**Issue by gammons** [FlatFilers/Guides#1093]
Hi, I am trying to learn all of these concepts for trying to use FlatFile and I gotta say, it's very complex and confusing.  Putting aside our very basic use case of "I just want to import CSVs of customer data", I am trying to learn about spaces, listeners, domains, events, etc. which seems overkill for what I am trying to do.

I'm going through the Getting Started guide, and I'm running into a lot of roadblocks.  

The first roadblock is on the [first page](https://flatfile.com/docs/apps/custom/tutorial-landing), where I need to set up the `red` namespace.  The directions say:

> In your Flatfile dashboard, click the + next to the Platform Apps header to create a custom app. Name is red for the sake of this demonstration.

...but when I log in, I'm not seeing anything that says "Platform Apps".  Nor am I seeing anything that would allow me to create a namespace called `red`.  Do namespaces == spaces?  Should I instead create a space called `red`?

Later, in the [configure a space](https://flatfile.com/docs/apps/custom/meet-the-workbook) page, there is verbiage that a space is equivalent to a domain.  

> Filter for a job by the domain (space) and the operation (configure) it was created.

Is a space a domain? Are domains important?  I can't seem to find info on the help site bout what a domain is.

Finally, I am stuck at the last step in the [Meet your space](https://flatfile.com/docs/apps/custom/meet-the-workbook#meet-your-space)

The tutorial says
> As you can see, this Space has a Workbook with a sheet and fields. A [Workbook](https://flatfileinc.mintlify.dev/docs/orchestration/workbooks) is like a template, it’s definition includes a profile of the data it expects to hold. We call that profile a Blueprint.

However, when I log into the app and click on the red space, I just get a message that an "empty space is created" :thinking: .  Am I supposed to see something in the app?

Wondering if I can get some help.  I'm worried that I just don't understand these concepts well enough to know if I'm doing things right.

**Comment by Arsik36** [comment]
Thank you for the feedback and for the details, this is very helpful. I think the issue is that your Account is on the old dashboard, which is why things seem very confusing. Our Getting Started guide is geared towards the new dashboard. <br><br>I will ask the team try and get you over to the new dashboard. Can you share with me an example environment ID from your account?

**Comment by gammons** [comment]
Thanks @Arsik36.   We're currently using v3.0 in production, so whatever we do, we'll need to keep that intact for the moment.

I thought I was using the correct platform.  I have a new that I'm using on platform.flatfile.com to go through the tutorial.  The environment ID I am using is `us_env_kAlKMNKc`.

**Comment by gammons** [comment]
Sure - 
![image](https://github.com/FlatFilers/Guides/assets/38560/f0c90934-8b21-4790-84d7-f68d078f9004)

**Comment by Arsik36** [comment]
If you change your URL from `/spaces` to `/dashboard`, do you see the new dashboard?<br>When you try, it may ask you to re login, and then take you back to the old dashboard. In that case, just try `/dashboard` again

**Comment by gammons** [comment]
ok yeah that worked.  I'm on a new page that looks much more intuitive.  What page was I on before?

**Comment by Arsik36** [comment]
You were on the old dashboard before. What I think happened is you created an Account when we did not have a new dashboard, that is why it defaults you to the old one. We will soon force default to the new dashboard. In the meantime, going from `/spaces` to `/dashobard` is the way to switch
