### ISSUE TITLE
Docs Feedback - Theming clarifications

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#119]
**Where:** https://flatfileinc.mintlify.app/advanced/theming
**What:** this may only be because I'm not a dev, but the instructions begin with "Start by simply updating theme.root.primaryColor and theme.sidebar.logo." - where do I find `theme.root.primaryColor` and `theme.sidebar.logo`? Should we add clarification here?

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/126
