### ISSUE TITLE
Docs Feedback - Guests or Collaborators?

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#123]
**Where:** https://flatfileinc.mintlify.app/advanced/guest_sidebar#metadata-sidebarconfig 
**What:** Throughout the docs, we have mentions of collaborators and guests - both terms referring to the same concept. I've only seen "collaborators" mentioned once so far in the docs, it looks like we are primarily using the term Guests - should we remove/change all the public mentions of "collaborators" to guests? or are we going to use two terms interchangeably (I would suggest we rather not). 

<img width="641" alt="Screenshot 2023-04-24 at 3 46 40 PM" src="https://user-images.githubusercontent.com/114111637/234113060-e6ed689c-56bc-4e2e-81a9-c976bb272539.png">

**Comment by ashleygmulligan2** [comment]
I think we should use Guest since this is what the API uses. Can you help me find the spots we say collaborators?

**Comment by ashleygmulligan2** [comment]
We are making changes here in support of this:

https://github.com/FlatFilers/X/issues/1201
https://github.com/FlatFilers/X/issues/1337

Thank you for your feedback.
