### ISSUE TITLE
Confusing experience with Workbook in the UI

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#125]
The confusion I noticed is that in the new docs, as the first step we say "Paste this cURL request to your terminal now to create a simple workbook". However, when that Workbook is created, in the Dashboard the Workbook is actually showing under Spaces tab.

As you will notice in the Loom video, the Dashboard shows 2 separate columns when we navigate under Spaces. One is Space Name, and the other is Workbooks. Spaces and Workbooks are different entities, as a Space can host multiple workbooks. So, it is confusing that we say we are creating a workbook, but in fact we are creating a space before introducing anything about Spaces. 

Note there is also a Created By value missing.

Here is a Loom video to shows my confusion - https://www.loom.com/share/4a93839ece16429daba0fc2a672bf67b

**Comment by ashleygmulligan2** [comment]
Thank you. We want to lead with Workbooks and the creation of them. Can you suggest some words for the UI so they know what to expect once they go into the UI and see a Space with the same name as their Workbook? We don't want to go deep on Spaces as it is irrelevant for many people.

**Comment by Arsik36** [comment]
If I am correct, it is not possible to have a Workbook created without it being a part of the Space. Therefore, if we want to lead with Workbooks, we need to include at least 1-2 sentences about Spaces to keep a customer informed as they go through the docs. Something I'd suggest in the docs, [in this specific part](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-a-workbook), is:

**Create a Workbook**
Every Workbook is a part of a Space - an designated collection of workbooks, data and files that are relevant to a specific customer or a project, for example (learn more about spaces here).

... and then have existing text continue

- Paste this cURL request to your terminal now to create a simple workbook or [run this command directly from our docs](https://flatfile.stoplight.io/docs/v10/tjt005wdogklo-create-a-sample-workbook).

- Login and see the workbook you created in your [Dashboard](https://platform.flatfile.com/?__hstc=71363532.c049b80a035a59d53887b98e986012c5.1682364577720.1682364577720.1682370472263.2&__hssc=71363532.7.1682370472263&__hsfp=3887566761).

The cURL command in fact creates a Space, not a Workbook. If you want to lead with a Workbook, then 1 way is to have a customer first create a Space in the UI, and then execute a cURL command to create a workbook attached to that space. Otherwise, we tell them to create a workbook but it gets created under spaces, and this becomes a confusing experience.

**Comment by ashleygmulligan2** [comment]
Thank you for your feedback. This is now more clear!
