### ISSUE TITLE
Issue on docs - 'Join community' link in the side nav sends you to a no longer active link

### ISSUE THREAD

**Issue by meganspaulding** [FlatFilers/Guides#1276]
Path: /starter-projects

When I click the 'Join Community' in the main, side navigation I get the following screen from slack:

<img width="1505" alt="Screenshot 2024-08-30 at 2 35 09 PM" src="https://github.com/user-attachments/assets/6e403710-2e64-422b-a831-e62bd34d7a1b">

**Comment by Arsik36** [comment]
Hey Megan, thanks for reaching out! We'll get that updated. In the meantime, if you click on this link: <a href='https://flatfile.com/join-slack/' target='_blank' rel='noopener noreferrer'>https://flatfile.com/join-slack/</a> does it work for you?
