### ISSUE TITLE
Docs Feedback - borked link "parsing error"

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#131]
Going from https://flatfileinc.mintlify.app/overview and clicking "Get Started →"
leads to: "🚧 A parsing error occured. Please contact the owner of this website." on the https://flatfileinc.mintlify.app/quickstart/meet-the-workbook page

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5686491/234118773-e8e86509-9664-4947-ba65-a315b55aa17d.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/5686491/234118829-78215b5e-c1ed-434a-b653-8d7588c15e3a.png">

**Comment by jasonhwolf** [comment]
fyi - refreshing the screen fixes the issue

**Comment by ashleygmulligan2** [comment]
It was a bug for a few minutes
