### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#133]
Path: /blueprint/properties

As a cleanup, we should make sure the URL matches (or is at least similar) to the title of this docs page. 

My suggestion:
* Set the URL to ` /blueprint/field-types`
* Change the title to `Field Types` (which is how it's referenced in /blueprint/overview)

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/137
