### ISSUE TITLE
Docs Feedback - dead link plugins.flatfile.com

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#136]
This is more of a reminder than anything else - 
We link out to https://plugins.flatfile.com on the quickstart/meet-the-workbook page... If this isn't available before soft launch, can we remove the broken link, or point it somewhere else?

**Comment by ashleygmulligan2** [comment]
Thank you, will mark as waiting on a merge.

**Comment by ashleygmulligan2** [comment]
This is now complete.
