### ISSUE TITLE
Docs Feedback - clarify what "go through a test import" means

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#138]
Path: /quickstart/meet-the-workbook

>Head to your [Dashboard](https://platform.flatfile.com/?__hstc=71363532.990777f428a77f31c1a47654ef0a93db.1681936940602.1681936940602.1682370603710.2&__hssc=71363532.3.1682370603710&__hsfp=2022379231) to see the workbook and go through a test import. After you finish importing, you should see the data appear in the Workbook sheet.

We should clarify what _exactly_ we expect the user to do when we say "go through a test import". If we literally just mean "upload a file", we should say that. Otherwise, if the user goes to upload a file, matches the column headers, and gets to the view of a spreadsheet and hits "complete" (where nothing happens) the experience seems broken.

**Comment by jasonhwolf** [comment]
And/or add some link to the "Configure a submit action" explainer (https://flatfileinc.mintlify.app/quickstart/submit-action)

**Comment by dboskovic** [comment]
Yeah this is a great idea. We've started listing off the steps to test things in some of the docs. Adding that here is good, and maybe even a gif.

**Comment by ashleygmulligan2** [comment]
Thank you, I've tried to update the verbiage to be more clear. Please try again.
