### ISSUE TITLE
Docs Feedback - no link to PubSub Client

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#139]
Path: /concepts/events

We call out, but never link to, the PubSub Client. If it's not supposed to be linked we should remove the bolding.
> The Flatfile **PubSub Client** is a super thin wrapper around the Flatfile API. It allows you to call our API after receiving events from any PubSub driver.

**Comment by ashleygmulligan2** [comment]
fixed in this PR: https://github.com/FlatFilers/Guides/pull/168
