### ISSUE TITLE
Docs feedback - add-data-transformation code mismatch

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#140]
Path: /quickstart/add-data-transformation

The `listener.js` code on this page doesn't match what's in `index.js` in replit.com, despite what the docs say to expect:
>The simplest event listener you could create looks like this. You’ll see this code in the repl.it link you forked above.

We should say something like "You’ll see see similar code in the repl.it link you forked above, which is less generic yada yada yada" 

The docs code:
```
export default function(flatfile) {
  flatfile.on('**', (event) => {
    console.log('-> My event', event.topic)
  })
}
```

vs (in the repo)

```
export default function(flatfile) {
  flatfile.on('records:*', (event) => {
    console.log('-> Handling my event', event.topic)
  })
}```

**Comment by ashleygmulligan2** [comment]
Thank you, we are working on this as we speak

**Comment by dboskovic** [comment]
This is resolved by updates to the repl.it example
