### ISSUE TITLE
Uploading csv results in blank screen

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#144]
Path: /quickstart/add-data-transformation

When trying to complete these two steps:

Manually add a few sample records
Try exporting [this CSV file](https://docs.google.com/spreadsheets/d/1hhTv_T2kRE6tmhEAZEk9TuJI_6B1Zd9r1Pw7Q3hTxuA/edit#gid=0) and uploading it into your workbook

I first manually created a couple of records, then tried to submit them but nothing happened. Then I downloaded the csv and dropped it onto the sheet with 2 records in it. The screen flashed and looked like it was taking me to the matching screen but it stopped before anything rendered. Blank page.

**Comment by dboskovic** [comment]
Hey @rjhyde - I'm unable to reproduce this. Can you share the spaceId this occured in and try to replicate again?

**Comment by rjhyde** [comment]
I've been unable to repro this all day. However I have seen this behavior before in the platform. I'll continue to try and repro this.

**Comment by ashleygmulligan2** [comment]
Thank you, please open a new issue in the X repo if you catch it again.
