### ISSUE TITLE
Docs feedback / Fresh eyes

### ISSUE THREAD

**Issue by MaerF0x0** [FlatFilers/Guides#148]
Was easiest for me to quickly record my thoughts in a google doc: https://docs.google.com/document/d/1krsqb5MHa6e9drlI_oHvmoUgFC0_NMw5mB_9hloq_2A/edit#

**Comment by ashleygmulligan2** [comment]
Thank you. I took care of most of these in PR: https://github.com/FlatFilers/Guides/pull/152
