### ISSUE TITLE
Issue on docs - Advanced > Theming

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#159]
Path: /advanced/theming

- Love the code snippet on the side!
- Would we be able to include an explainer of would the code example be incorporated into their configuration?

**Comment by elisadinsmore** [comment]
Adding to this: images with text are pretty small and I can barely read the included text on a large monitor. 

![image](https://user-images.githubusercontent.com/106406547/234361157-6bd6bded-be89-44ce-9132-3f9e6fd33afa.png)

If they need to stay this small, could we make text larger or unnecessary?

**Comment by elisadinsmore** [comment]
Do we have anywhere that lists what all can be included in the metadata?

**Comment by ashleygmulligan2** [comment]
Hey @elisadinsmore everything that can be included in metadata is that list above. Can you ask me that question another way? I'm likely not understanding.

I agree some of the text is too small, we will get those updated soon.

@colinfrederickson I will update the code snippet to show it working inside a listener, would that be more clear?

**Comment by elisadinsmore** [comment]
@ashleygmulligan2 got it! My question was essentially - is there anything else that can be included in metadata _other_ than theme information, or is it always going to be just this?

```
metadata: {
      theme: {
        //... 
      }
    }
~~~

**Comment by ashleygmulligan2** [comment]
I see, you can also add a guestsidebar but I show that in a separate example. I'd like to not show the rest here because it's a moving target. I made the other updates here: https://github.com/FlatFilers/Guides/pull/171

**Comment by colinfrederickson** [comment]
@ashleygmulligan2 - that would make it more clear!
