### ISSUE TITLE
Security > Roles and Permissions Thought/Opinion

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#161]
As a support person who will likely get questions around this, I recommend not including language like "at this time" in docs unless there's a clear timeline for when alternatives will be built in and available for customers to use. Otherwise we'll get lots of questions about timelines, and if any projects about alternative ways to workbook guest roles are abandoned, we'll have to go back and edit this anyways. 

https://flatfileinc.mintlify.app/security/roles-and-permissions#workbook-grant

> Role | Details
> 
> Single-Workbook Guest | This role is for someone that should only be able to see a single workbook inside a Space. This role can only be configured in code at this time.
> Multi-Workbook Guest | This role is for someone that has access to more than one workbook inside a Space. This role can only be configured in code at this time.

**Comment by ashleygmulligan2** [comment]
Great feedback, thank you. Fixed in this PR: https://github.com/FlatFilers/Guides/pull/170
