### ISSUE TITLE
Clarification/question on Developer Tools > Core Libraries > Listener

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#162]
The record hooks here are formatted differently than the hooks shown in the quickstart. They don't use the `@flatfile/plugin-record-hook`, for starters. 

- Why are these different? 
- Is there a preferred method of handling data hook type validations? 
- Will there be any explanation about the differences between the Quickstart examples and examples here?

**Comment by ashleygmulligan2** [comment]
1. These are currently different because we built these examples before that plugin existed. 
2. The preferred method is to use the plugin

I will remove these example for now until we get them using the plugin.

Thank you. Fixed in this PR: https://github.com/FlatFilers/Guides/pull/169
