### ISSUE TITLE
Quickstart > Step 2 > CLI referenced but not linked

### ISSUE THREAD

**Issue by howarddierking** [FlatFilers/Guides#181]
Path: /quickstart/add-data-transformation

the `flatfile` CLI is referenced, but not linked. The narrative then just keeps going. Recommend removing the mention until we're ready to actually talk about it, but if we want to keep the reference, it should be hyperlinked to the documentation where we actually address it.

**Comment by ashleygmulligan2** [comment]
https://github.com/FlatFilers/Guides/pull/185
