### ISSUE TITLE
Missing starter code for developers to build upon

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#205]
Path: /core-paths/embedding

In the Spotlight documentation, [we have this starter code ](https://flatfile.stoplight.io/docs/platform-sdk-mono/d6ff961604945-flatfile-react#space-component) that allows developer to see what they can build on top. I am reading the new documentation, and [under this section here](https://flatfileinc.mintlify.app/core-paths/embedding#build) we explain what `useSpace` does without showing any code on where this is from and how to get started with Flatfile. This is where I am already completely lost reading the docs.

When I scroll down I see some 5-liner code snippets, but they don't help me get started. Skeleton code will be EXTREMELY helpful :)

**Comment by ashleygmulligan2** [comment]
Thank you, this page is still in progress and hidden now.
