### ISSUE TITLE
Missing "Security" header?

### ISSUE THREAD

**Issue by sky-lackner** [FlatFilers/Guides#224]
Path: /developer-tools/security/authentication

Is "Security" meant to have its own header and link in this list? 
![image](https://user-images.githubusercontent.com/7275446/235230784-f25802ed-9733-44da-9fa8-c45ba284e891.png)

It's kind of weird that the "Developers" header links to a page with "Security" at the top. 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/7275446/235231048-b32e50ba-bdb1-40f1-b078-83570343ac87.png">

**Comment by ashleygmulligan2** [comment]
It's just a child of the Developers area so it shouldn't show up in the top menu area
