### ISSUE TITLE
Quickstart: Workbook; when I click on the OpenAPI plugin, I get an invalid page

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#228]
Path: /quickstart/meet-the-workbook

**Comment by bigcountrycrane** [comment]
I would love to use my own OpenAPI schema to test this, but when I click on the OpenAPI plugin https://code.treez.io/docs/customer-apis, I get an invalid page. I guess I'll follow the tutorial.

https://docs.google.com/document/d/1f3JZQNvQJJzyEUO0ZO_YGnRyA0KKQcESyzM3OM7iQ7o/edit

**Comment by ashleygmulligan2** [comment]
Thank you, fixed.
