### ISSUE TITLE
Quickstart: Transformation - "Flatfile CLI" is a dead link, and I don't see a page for the CLI basics

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#230]
Path: /quickstart/add-data-transformation

When I click on "Flatfile CLI", though, I get taken back to the homepage.

https://docs.google.com/document/d/1f3JZQNvQJJzyEUO0ZO_YGnRyA0KKQcESyzM3OM7iQ7o/edit

**Comment by ashleygmulligan2** [comment]
Thank you, I fixed the link. We will add a page here asap.
