### ISSUE TITLE
Quickstart: Transformation - email validation does not work

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#233]
Path: /quickstart/add-data-transformation

I update my code to use the email validator, but when I go back to the sheet and type in something that should be invalid - in my case "doob" - I don't see anything happen. Looks like Flatfile still thinks the value is valid.  I did happen to go back to the replit and see an error in the console: Error getting records: ReferenceError: EmailValidator is not defined

https://docs.google.com/document/d/1f3JZQNvQJJzyEUO0ZO_YGnRyA0KKQcESyzM3OM7iQ7o/edit

**Comment by ashleygmulligan2** [comment]
you needed the import up top, fixed the docs
