### ISSUE TITLE
Examples for Sheets don't really make sense

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#234]
Path: /blueprint/overview

<img width="603" alt="image" src="https://user-images.githubusercontent.com/110071258/235240100-07510131-99fa-46ea-87b5-4a5bbf2594fd.png">
by saying a person, a company it seems like this is just one thing instead of a group of similar things. I would change to something like "A collection of fields that describe a single entity (eg. people, products, companies)." especially since in the code example your sheet is called "products"

**Comment by ashleygmulligan2** [comment]
Thank you, fixed in this PR: https://github.com/FlatFilers/Guides/pull/250
