### ISSUE TITLE
Update Key & Label example to make sense with one another

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#236]
Path: /blueprint/field-types
<img width="333" alt="image" src="https://user-images.githubusercontent.com/110071258/235241993-316ecfb1-9a73-4d31-a530-187795424e55.png">

In the string example, the key and label don't make sense with one another. Change Key to "sku" or "item number" or something like that

**Comment by ashleygmulligan2** [comment]
Thank you, fixed this in: https://github.com/FlatFilers/Guides/pull/249
