### ISSUE TITLE
Date Field Description

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#244]
Path: /blueprint/field-types

<img width="748" alt="image" src="https://user-images.githubusercontent.com/110071258/235253292-29bb54f3-dd94-4e38-af9b-cc57ed2ea761.png">

This is really confusing to me. Can date fields ONLY be converted to that format or can I use a data hook to convert it to another format?

I also think we should leave out the datetime piece or change it to "Datetime is not supported at this time."

**Comment by colinfrederickson** [comment]
mentioned [here](https://github.com/FlatFilers/Guides/issues/160) as well!
