### ISSUE TITLE
Matching engine?

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#254]
Path: /blueprint/relationships

<img width="744" alt="image" src="https://user-images.githubusercontent.com/110071258/235260626-bb06e502-6991-4269-bec2-8a23b65523a5.png">
Are we referring to a user matching when talking about the matching engine here? There's nowhere else we talk about a matching engine so this is confusing.

**Comment by ashleygmulligan2** [comment]
fixed here: https://github.com/FlatFilers/Guides/pull/583
