### ISSUE TITLE
Schema Converter Plugins

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#255]
Path: /quickstart/meet-the-workbook

<img width="746" alt="image" src="https://user-images.githubusercontent.com/110071258/235260946-4c5de827-d6fa-43a0-b5f9-b7fef59a9a49.png">

Will these be available for soft launch? I don't think we should reference them if none will be available like they are now.

**Comment by ashleygmulligan2** [comment]
plugin-json-schema will be
