### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#260]
Path: /quickstart/meet-the-workbook
<img width="679" alt="image" src="https://user-images.githubusercontent.com/110071258/235262329-f2fa04cc-0998-4beb-ac87-efacb8638bfb.png">

is transform the right word here? There's no data hooks in the sheet yet so you're just editing...

**Comment by ashleygmulligan2** [comment]
Thank you, fixed in this PR: https://github.com/FlatFilers/Guides/pull/261
