### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Noelle-FF** [FlatFilers/Guides#264]
Path: /quickstart/meet-the-workbook

Super minor but I noticed in some places Workbook and Spaces are capitalized and in some they are not. I'm not sure which is correct but just wanted to call that out. I have a screenshot but I don't think I'm able to attach here.

**Comment by Noelle-FF** [comment]
Can you see this?
<img width="300" alt="Screenshot 2023-04-28 at 3 33 58 PM" src="https://user-images.githubusercontent.com/111616392/235264944-5b56de07-0a4e-4125-80e6-fc27c56f8941.png">

**Comment by ashleygmulligan2** [comment]
Feel free to lowercase where you see it via the edit button

**Comment by Noelle-FF** [comment]
<img width="1087" alt="Screenshot 2023-04-28 at 3 46 04 PM" src="https://user-images.githubusercontent.com/111616392/235265885-36fea939-0389-4e1d-ac1f-0c83cd34a8cc.png">

I don't think I am able to

**Comment by ashleygmulligan2** [comment]
Yes, closing since discussed offline.
