### ISSUE TITLE
Issue on docs - Schemas

### ISSUE THREAD

**Issue by Noelle-FF** [FlatFilers/Guides#265]
Path: /quickstart/meet-the-workbook

"Using Schemas" I don't believe schema needs to be capitalized here
<img width="474" alt="Screenshot 2023-04-28 at 3 43 57 PM" src="https://user-images.githubusercontent.com/111616392/235265672-88bd5420-c17c-4ca8-a40b-95369b7a1433.png">

**Comment by ashleygmulligan2** [comment]
thank you, fixed in this PR: https://github.com/FlatFilers/Guides/pull/321
