### ISSUE TITLE
Capitalization Consistency

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#266]
Can we get consistent on our capitalization in the navigation here 
<img width="261" alt="image" src="https://user-images.githubusercontent.com/110071258/235265849-3f47bf85-575e-485c-a4d1-be53d026af17.png">

**Comment by ashleygmulligan2** [comment]
thank you, i'm trying to do all lowercase. I will fix.

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/326

**Comment by ashleygmulligan2** [comment]
Fixed
