### ISSUE TITLE
Flatfile Dashboard Feedback

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#272]
- Should the "Getting started guide" link on the platform.flatfile.com/spaces page now link to this [page](https://flatfileinc.mintlify.dev/docs/quickstart/meet-the-workbook)?

- The "Configure a Space to get started" message is a bit confusing considering the quick start has the user configure a Workbook to get started.  Would "Configure Flatfile to get started" or something non space or workbook specific?

Page section for reference:

![Screen Shot 2023-04-29 at 9 40 05 AM](https://user-images.githubusercontent.com/110066636/235311181-93f0b14c-6d46-4f09-983a-fa8fcdc7e40d.png)

**Comment by howarddierking** [comment]
That seems like the right thing to me. @ashleygmulligan2 ?

**Comment by ashleygmulligan2** [comment]
Correct, @dboskovic is working on in-app things today. Tagging him for vis
