### ISSUE TITLE
Issue on docs: provide better guidance on adding record hook code.

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#274]
Path: /quickstart/add-data-transformation

When we provide the record hook code, we don't provide guidance on how to add this code to the existing index.js file they have created before. We should provide some guidance for them to replace the existing listener function with this new one.

**Comment by ashleygmulligan2** [comment]
Can you help me here? I show the full file and how it should look but maybe there's more context needed?

**Comment by rjhyde** [comment]
I think something similar to what you are using in the other sections:

`Modify your default export function in Repl.it to add this transformation as shown.`

**Comment by hansjhoffman** [comment]
Not sure how much this has changed since this issue was created, but is it possible this has been resolved? 

<img width="779" alt="Screenshot 2023-07-07 at 10 33 13 AM" src="https://github.com/FlatFilers/Guides/assets/9221098/e095fa25-7199-4d59-b440-d1c76575b8d4">

**Comment by ashleygmulligan2** [comment]
agree!
