### ISSUE TITLE
Issue on docs: recordHook code and infinite loop of listener.use

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#275]
Path: /quickstart/add-data-transformation

Once the listener.use recordHook kicks in, the console.log is constantly scrolling with messages. If that's expected behavior we should call that out in the docs so that user is not alarmed.

Otherwise, user is thinking:
- Did I break something?
- How do I stop the scroll?
- If this is normal, what is it doing?
- Is this chewing up resources and slowing everything down?
- I'm not doing anything, why is it still going?

**Comment by ashleygmulligan2** [comment]
That is not expected behavior.

**Comment by ashleygmulligan2** [comment]
This is now fixed
