### ISSUE TITLE
Issue on docs: adding transformation, include more explanation of what's happening.

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#276]
Path: /quickstart/add-data-transformation

When the recordHook runs for the first time, it does what the text says it will do but it also changes all the other records. We should mention that behavior so the user better understands that recordHooks work on all the records, not just the new record you add.

**Comment by ashleygmulligan2** [comment]
great, agree. Will get that updated.

**Comment by hansjhoffman** [comment]
This page references the `@flatfile/record-hook-plugin` which does describe its usage. Could we say that is sufficient?

**Comment by ashleygmulligan2** [comment]
agree!
