### ISSUE TITLE
Issue on docs: using your validation

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#278]
Path: /quickstart/add-data-transformation

When I use the email validator, nothing happens. EmailValidator is not being imported.

Need to add this line to the example code:

`import * as EmailValidator from 'email-validator';`

**Comment by colinfrederickson** [comment]
Appears similar to https://github.com/FlatFilers/Guides/issues/233

**Comment by ashleygmulligan2** [comment]
Fixed!
