### ISSUE TITLE
Navigation Issue + Spaces

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#279]
Not sure if this falls under the happy path, so feel free to move this out of the bug bash.

Scenario:

- deployed first [workbook](colin+april29QS@flatfile.io) to the development environment
- navigated to Flatfile to confirm the workbook exists in the "Spaces" Dashboard
- confirm space exists in list of spaces
- while in Flatfile, changed to the production environment
- decided to log out while in the production environment
- when logging back in, am logged into the production environment and greeted with the Configure a Space to get started
- when navigating the the development environment, greeted with the Configure a Space to get started screen - not the spaces dashboard with the listed space that existed before
- Need to reload platform.flatfile.com/spaces to see list of spaces.

Loom of experience: https://www.loom.com/share/d2a4f886664e41f1a2d93ce5ff0cd5b7

What is the expected behavior for the last step in this flow? Personally was expecting to see the list of spaces like in step 3.

**Comment by ashleygmulligan2** [comment]
Thank you, let's report this in the X repo as this is core platform issue. Just copy paste this exactly, thank you.
