### ISSUE TITLE
Quickstart: submit action

### ISSUE THREAD

**Issue by rjhyde** [FlatFilers/Guides#281]
The submit action does not send the data of the sheet to the webhook.site.

But in step 2 of the quickstart, we state this:

_Next, we will [add an action](https://flatfileinc.mintlify.dev/docs/quickstart/submit-action) that submits data from this Sheet to your API._

Can we clean up the wording here to set expectations correctly?

**Comment by ashleygmulligan2** [comment]
Ah, you're saying it just hits that endpoint but doesn't actually send data, right?

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/320
