### ISSUE TITLE
Issue on docs - Setting up a listener includes events with missing definitions

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#282]
Path: /quickstart/add-data-transformation

When making a change to a first name in the Flatfile UI, the listener returns the following:

sheet:validated us_evt_hn2g13E7nbLxnfAn 4/29/2023, 5:04:19 PM
sheet:updated us_evt_hypL7L7y9odTm3xV 4/29/2023, 5:04:19 PM
record:updated us_evt_r2PX1MVdtMygUJ43 4/29/2023, 5:04:19 PM
records:updated us_evt_NUep8z4txOLe2pQc 4/29/2023, 5:04:19 PM
commit:created us_evt_1T67givNdXmpooGU 4/29/2023, 5:04:19 PM
-> My event sheet:validated
-> My event sheet:updated
-> My event record:updated
-> My event records:updated
-> My event commit:created

I was not able to find definitions for the following events in the [docs](https://flatfileinc.mintlify.dev/docs/concepts/events):

sheet:validated
records:updated (is this the same as record:updated?)

Could these get added?

**Comment by ashleygmulligan2** [comment]
Thank you, this was a mismatch with our event renaming work that is now live. Check now.

**Comment by colinfrederickson** [comment]
These are the events I've gotten back:

sheet:validated us_evt_AVIncPZSHHujrMWh 4/30/2023, 5:38:05 PM
sheet:updated us_evt_QYe6XD9w7tIMFN4L 4/30/2023, 5:38:05 PM
commit:created us_evt_bRf7QN2D6D8x4NSy 4/30/2023, 5:38:05 PM
records:updated us_evt_3Y7VlCQsZ2qzJ0E3 4/30/2023, 5:38:05 PM
record:updated us_evt_sWGxRHToHWjCZqf6 4/30/2023, 5:38:05 PM
sheet:validated us_evt_xJl1Huq7goztLcmS 4/30/2023, 5:38:04 PM
sheet:updated us_evt_jtU0GnDBBXjSE0kS 4/30/2023, 5:38:04 PM
records:updated us_evt_QxIMlMYemKto19DS 4/30/2023, 5:38:04 PM
record:updated us_evt_otHOnYMyLmhlJjqa 4/30/2023, 5:38:04 PM
commit:created us_evt_SayuDd4HIAXl5x7q 4/30/2023, 5:38:04 PM
-> My event sheet:validated
-> My event sheet:updated
-> My event records:updated
-> My event record:updated
-> My event commit:created

couple of questions:

- what is the difference between records:updated and record:updated?
- definitions for sheet:validated and records:updated do not appear in the docs. Were those the events that were renamed?

**Comment by ashleygmulligan2** [comment]
oh i see, thank you. @bangarang or @srmotter can you assist here?

**Comment by ashleygmulligan2** [comment]
It seems you are using an account that was setup before the event naming was in production last Wednesday/Thursday. You're seeing a mixture of old and new event names since it was a non-breaking change.

**Comment by colinfrederickson** [comment]
oh interesting. I set this FF account up yesterday during testing and re-forked the replit yesterday as well. what would the expected event names be?
