### ISSUE TITLE
Issue on docs - Deploying

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#286]
Path: /quickstart/deploying

- Didn't I just deploy to Flatfile - how is this different?
- For this step, are we trying to communicate that the user doesn't need to use repl.it to deploy to Flatfile?
- Provide example (mentioned [here](https://github.com/FlatFilers/Guides/issues/285) - what will this example include?

**Comment by ashleygmulligan2** [comment]
Agree, try now. I made changes here: https://github.com/FlatFilers/Guides/pull/312
