### ISSUE TITLE
Hover details for entities

### ISSUE THREAD

**Issue by brentkulwicki** [FlatFilers/Guides#323]
What if for the entities, we had a one sentence overview in the hover with it being clickable to get a more detailed overview? 

![image](https://user-images.githubusercontent.com/37881163/235369108-92ed0bcc-de12-4287-a9f5-d55ecc7af1e1.png)

![image](https://user-images.githubusercontent.com/37881163/235369145-e50750bc-c1a8-4c4c-bea5-7f32a31340a9.png)
Example, there is no hover here on workbook, but utilizing that effect to give a brief explanation would be valuable.

**Comment by ashleygmulligan2** [comment]
That would be amazing, can you PR this for me?

**Comment by ashleygmulligan2** [comment]
There's probably 20 places to update

**Comment by ashleygmulligan2** [comment]
Thank you for doing this @wiafe . Closing
