### ISSUE TITLE
Sample file and schema are too simple

### ISSUE THREAD

**Issue by RyanDriscoll** [FlatFilers/Guides#332]
The sample schema and file [here](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook) could have more elements that show off flatfile functionality. some ideas:

- [ ] change column names in sample file so auto mapping is cooler
- [ ] add some different field types with some basic validation, required or unique

**Comment by ashleygmulligan2** [comment]
Agree! We wanted to go super basic in the quickstart. However, we should add these in a better breakdown of schemas in the Blueprint area. Closing this and will beef up Blueprint soon.
