### ISSUE TITLE
Organize the plugins page so you see available plug ins first

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#357]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/110071258/235378658-dc16f8e3-7d54-4294-9189-cc2c52be77f4.png">
should see available plug ins first so they don't have to page through coming soon

**Comment by ashleygmulligan2** [comment]
Thank you, related to : https://github.com/FlatFilers/Guides/issues/284 - tracking over there
