### ISSUE TITLE
Create Space in API doesn't mention Blueprint, only SpaceConfig

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#362]
https://flatfile.stoplight.io/docs/v10/25e20c8ab61c5-create-a-space

As a developer, the only way I can create a Space with a Blueprint is by following the Getting Started guide (running the CURL command to create the initial Blueprint). The API docs still reference SpaceConfig which isn't covered anywhere in the documentation.

**Comment by ashleygmulligan2** [comment]
SpaceConfig is optional in the API reference, yea? You can make a workbook inside a listener, too. What am I missing because I'm sure you're onto something.

**Comment by ashleygmulligan2** [comment]
We are adding schema: {} as a wrapper around sheets when creating Workbook but that work is not yet complete.

**Comment by bigcountrycrane** [comment]
Creating a "Workbook" isn't the same as creating a "Space".

**Comment by bigcountrycrane** [comment]
For example, right now our customers may create one or more "Blueprints" that are templates for a "Workbook" that will be used in a project "Space". That project "Space" would be created when the customer's workflow dictates it, and done either by a user clicking "Create Space" in the dashboard or via an API call to create the Space. The latter would happen if, for example, our customer ran a script from Salesforce after each new customer was closed.

**Comment by ashleygmulligan2** [comment]
Let's revisit this now with all our changes and see if you still have same feeling. Want to resolve this with you.
