### ISSUE TITLE
Modifying code example to not prematurely introduce REQUIRED concept

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#368]
In the current code snippet  below ...

```
import { recordHook } from '@flatfile/plugin-record-hook';

const validEmailAddress = /^[\w\d.-]+@[\w\d]+\.\w+$/;

export default function(listener) {
  listener.use(recordHook('contacts', (record) => {

    let emailAddress = record.get('email');
    if (!validEmailAddress.test(emailAddress)) {
      record.addError('email', 'Invalid email address');
    }

    return record
  }))
}

```
the code unintentionally is making email address a required field - a feature I think we are not looking to introduce in this code snippet. I modified the above code to add an additional IF statement. It check if there is a value in the Email field. If there is, do the validation. If the value is null, then don't validate it. 

Otherwise, if a value is present on another field in this row, it also validates null values in the Email field, making it a required field. Code below just keeps things to the point without introducing new concepts.

```
import { recordHook } from '@flatfile/plugin-record-hook';

export default function(listener) {
  
  listener.use(
    recordHook('contacts', (record) => {
      const value = record.get('firstName')?.toString()
      if (value) {
        record.set('firstName', value.toLowerCase())
      }

    let emailAddress = record.get('email');
    if (!validEmailAddress.test(emailAddress)) {
      record.addError('email', 'Invalid email address');
    }

      return record
    })
  )
}
```

If you agree with my logic to modify the code to NOT require email field if a value in another field is present, please test on your end to ensure my code executes correctly for you too

**Comment by ashleygmulligan2** [comment]
Happy to update this with you if still an issue
