### ISSUE TITLE
Impossible to create a space with no spaceConfig, docs don't introduce spaceConfig

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#369]
I found an issue whereby if you go to the UI and want to create a Space, you won't be able to without spaceConfig. However, QuickStart or new docs don't introduce spaceConfig. So, it is not possible to create a Space for a new developer using Listener docs.

**Comment by ashleygmulligan2** [comment]
we are tracking this in the X repo, thank you https://github.com/FlatFilers/X/issues/1843
