### ISSUE TITLE
Docs Feedback - Access page error 

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#376]
**Where:** https://flatfileinc.mintlify.app/blueprint/access 
**What:** page shows an error: 
<img width="799" alt="Screenshot 2023-04-30 at 7 44 21 PM" src="https://user-images.githubusercontent.com/114111637/235384245-9987f748-53c8-4b9a-9a35-80260e65918b.png">

**Comment by ashleygmulligan2** [comment]
This is now resolved
