### ISSUE TITLE
Docs Feedback - Deploying more than once

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#377]
**Where:** https://flatfileinc.mintlify.app/developer-tools/deploying#deploying-more-than-once
**We say:**

> In most getting started examples, we are focusing on the workbook; however, you can deploy any change to your code at any time.
> For example, if you are just needing to add a sheet to an already existing workbook, simply deploy again with the added sheet and everything will update.

Are there any cases where changing/updating code will have consequences? Are there changes that can be made that will not be visible in the already existing workbook? This is the time and place to outline those here.

**Comment by ashleygmulligan2** [comment]
Handle in @meritmalling latest PR
