### ISSUE TITLE
Docs Feedback - missing text?

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#378]
**Where:** https://flatfileinc.mintlify.app/developer-tools/environment

**What:** seems like part of the text is missing or maybe it's a sentence that did not get deleted all the way? 
<img width="831" alt="Screenshot 2023-04-30 at 7 55 19 PM" src="https://user-images.githubusercontent.com/114111637/235384860-3550cb1a-2e8a-4b16-8d4d-cfaff0d72532.png">

**Comment by ashleygmulligan2** [comment]
Thank you, fixed
