### ISSUE TITLE
"Run this command directly from our docs" link broken

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#387]
On [Quickstart > Meet the Workbook](https://flatfileinc.mintlify.dev/docs/quickstart/meet-the-workbook), under "Create a Workbook", there is a link that says "run this command directly from our docs". When I click on this link it brings me to this Stoplight page that says "Page not found": https://flatfile.stoplight.io/docs/v10/tjt005wdogklo-create-a-sample-workbook

**Comment by ashleygmulligan2** [comment]
Thank you, you're so fast. I was working right then.
