### ISSUE TITLE
Success message after cURL request

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#392]
A success message (similar to the ones we get on `npx run deploy`)would be nice after I run the cURL request. If i'm not technical, I'm left wondering if that really did anything until I go into the UI and see that the space/workbook has been created.

**Comment by hansjhoffman** [comment]
Understand the end goal with your request, but as long as we stay with `curl` commands in the docs we won't get "pretty" messages like our custom CLI program/script. 

@ashleygmulligan2 I recommend we close this

**Comment by ashleygmulligan2** [comment]
This is more of a core platform issue, @hansjhoffman do you want to move this to platform-sdk-mono > cli ? I say you self-assigned.

**Comment by madaley1** [comment]
Hey @ashleygmulligan2, do we still have any active curl requests in the docs, or can this be closed? I think I remember them being removed but want to verify before closure.

**Comment by ashleygmulligan2** [comment]
@Arsik36 can you move this to a regular issue
