### ISSUE TITLE
Include information on setting process.env. variables on launch in Embedded Docs

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#404]
V3 has the ability to set environment variables that are then used in Data Hooks: https://flatfile.com/versioned-docs/3.0/guides/embed/#environment-variables 

Some customers also use this option to pass in authentication keys they will end up needing for API calls in their data hooks, and need an equivalent in X. From [this thread](https://flatfile.slack.com/archives/CTVRSGLF8/p1682973272262969?thread_ts=1682967344.699229&cid=CTVRSGLF8), they should be able to set process.env.SECRET in their code to set these keys while deploying the agent. Instructions on how to set these variables and use them after launching their Portal should be included in the documentation.

**Comment by mairechew** [comment]
Chatting w/ @bangarang on how this would be possible.

**Comment by ashleygmulligan2** [comment]
@elisadinsmore can you move this to regular triage/feature requests?
