### ISSUE TITLE
Listener Deploying to Incorrect Environment

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#408]
seeing some funky behavior when deploying using npx flatfile@latest deploy --token=YOUR_SECRET_KEY and following the deploy guidance [here](https://flatfileinc.mintlify.dev/docs/quickstart/deploying)

i’m using the secret key from my **projectonboardingtest** environment in the command, but my listener is being deployed into a completely separate environment in my account **dev**

✔ Code package compiled to .flatfile/build.js
✔ Code package passed validation
✔ Environment "dev" selected
✔ Event listener deployed and running on your environment "dev". us_ag_wUDhkj1f

**Comment by ashleygmulligan2** [comment]
This is now resolved
