### ISSUE TITLE
Data Checklist Requires Primary Workbook to be set

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#409]
When following the deploy guidance [here](https://flatfileinc.mintlify.dev/docs/quickstart/deploying), spaces created do not have a primary workbook assigned. 

![Screen Shot 2023-05-01 at 8 28 04 PM](https://user-images.githubusercontent.com/110066636/235566765-f39436da-dc47-4b24-ac66-9feb6574eba2.png)

Is there a recommended best practice for assigning a primary workbook when:

1. spaces are created and then workbooks are attached
2. spaces are created in the UI from space configurations

**Comment by ashleygmulligan2** [comment]
Yea you have to set the primary with an update after workbook is made. We are working on a better fallback in the UI, too
