### ISSUE TITLE
Egress + supporting functionality to get records

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/Guides#417]
<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b2fik)

**Comment by howarddierking** [comment]
@ashleygmulligan2 - if this is merged, would you mind updating the GA Project status? Either in progress or done depending on whether you want until this is closed before marking done.
