### ISSUE TITLE
Deploy feedback

### ISSUE THREAD

**Issue by dboskovic** [FlatFilers/Guides#42]
Path: /developer-tools/deploying

- [x] Improve the CLI defaults so no `.flatfilerc` is required - at the very least we only need an API key now
- [x] `npm run deploy` only works if you're in our example repo. This should be changed to the `npx flatfile publish` command and made to work.
- [x] We haven't introduced the `cli` yet here at all. We should most likely do that sooner.

**Comment by ashleygmulligan2** [comment]
This work is being completed in the CLI, which is in the platform-sdk-mono repo. That work is in progress and clear so closing this. Thank you.
