### ISSUE TITLE
When does the event "file:updated" happen?

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#425]
Path: /concepts/events

Based on the documentation, I see it says `Called when a file is updated. For example, when a file has been extracted into a workbook.` What does the part `when a file has been extracted into a workbook` mean? I am trying to trigger this event after defining it in my PSDK like so:

```
  listener.on('file:updated', (event) => {
    console.log('File updated', event.topic)
  })
```

But I cannot get this to trigger. Once I can get it to trigger, I can help simplify the definition of this event in the docs.

**Comment by ashleygmulligan2** [comment]
This would using XLSX extractor where you're going to upload an XLSX file, and it will extract. That event should fire then.
