### ISSUE TITLE
`Required` on field options may not be visible enough between other text

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#445]
Path: /blueprint/field-types

I just helped a customer who could not deploy his cURL command to create a workbook alongside a blueprint. The issue was that they had many enum fields, but they did not specify `config.options` for them. Even though we state `required` when necessary, if you look at the documentation, `required` can get lost in the middle of other text around. 

The customer did not provide a suggestion, but my thinking is to maybe make `required` options more explicit and visible by having a background color to them? For example, consider the screenshot below. I am picturing a green box like this for `required` options to help visually navigate users to most important options a field type must have to be deployable.

<img width="760" alt="Screenshot 2023-05-17 at 5 15 49 PM" src="https://github.com/FlatFilers/Guides/assets/61366150/f799cb20-03da-4c51-9d35-2f54a84b52b4">

**Comment by ashleygmulligan2** [comment]
Thank you, yea, I can see that, can you point me to an anchor on the page you are referring to

**Comment by Arsik36** [comment]
<img width="777" alt="Screenshot 2023-05-31 at 3 16 03 PM" src="https://github.com/FlatFilers/Guides/assets/61366150/85fea8b1-fe03-41d0-bcfb-4359af960b41">

it would be here - https://flatfile.com/docs/blueprint/field-types#enum

**Comment by ashleygmulligan2** [comment]
ah we cannot alter this design, it's a built in component, will give this feedback tho to vendor
