### ISSUE TITLE
Need clearer instructions on primary and pinned workbooks

### ISSUE THREAD

**Issue by jmmander** [FlatFilers/Guides#467]
Primary - how to set the `primaryWorkbookId` on the space and how this interacts with the data checklist
Pinned - a label on the workbook that dictates the order of workbooks in the sidebar. I think this is already in the docs but just needs to be updated to use `pinned` insead of `primary`

Should be made clear that they are different things

**Comment by ashleygmulligan2** [comment]
fixed here: https://github.com/FlatFilers/Guides/pull/617 - primary not a thing anymore
