### ISSUE TITLE
Under Enums, we should stress label is required, instead of providing a default value.

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#479]
Path: /blueprint/field-types

Right now, we don't specify a "label" is required and provide a default for it instead. This is problematic, because if a customer doesn't specify a "label" and match enums at mapping stage, in the grid they will see `undefined` in the rows. This leads to a bug-like behavior. 

I suggest we remove default value and make label required

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_arjpo)

**Comment by ashleygmulligan2** [comment]
Do you think your PR above covers this or do you want more work to be done?

**Comment by brentkulwicki** [comment]
Just looking at this one. 1) I am not sure this belongs in guides, but rather seems like a quick TT fix (maybe?) 2) I don't know that the answer is to make labels required, but we should use the values if no labels are provided here. 

Thoughts @ashleygmulligan2 @Arsik36 ?

**Comment by madaley1** [comment]
Currently this is labeled as required. Is any work necessary here? @ashleygmulligan2 @Arsik36 
![image](https://github.com/FlatFilers/Guides/assets/61160473/d1dc4227-fc93-42bc-987b-ecb8105a6903)
