### ISSUE TITLE
Example: Configure Latest Version in a Node project

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#490]
As we build out examples, we've had requests to display an example of embedding the importer and creating/updating blueprints in a node project. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b0frg)

**Comment by ashleygmulligan2** [comment]
can you add this to product signals please?
