### ISSUE TITLE
Remove warning re: blueprint relationships

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/Guides#499]
there is a warning that says:
This is not comparable to a foreign key. There should be no specification of which column to reference as it is multi-variate. A user may establish a relationship in mapping with a soft reference like a company name. Once stored in our system, we will reference by our internal IDs, and on egress we provide the known system_id if available.

but there is a column specification? isn't that what config.key is? but then config.key is in the example but not listed under configuration options

This should no longer be a warning

**Comment by madaley1** [comment]
Relationships guides could definitely use some sprucing up. I think removing the warning alone isn't quite enough, so I may make some extra additions while working on this one.
