### ISSUE TITLE
Ashley's version showing when creating a workbook from docs

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#50]
When you go to create a workbook from the docs in step 1 of the quick start it shows as Ashley's version
<img width="303" alt="image" src="https://user-images.githubusercontent.com/110071258/234048739-350ef6a6-eff9-4034-bd24-dcfa5b8a111f.png">

**Comment by ashleygmulligan2** [comment]
I haven't merged my new branch in Stoplight docs yet since we aren't live. This will fix itself once that page is on main.

**Comment by ashleygmulligan2** [comment]
This is now merged in this PR: https://github.com/FlatFilers/X/pull/1734
