### ISSUE TITLE
has-one vs has-many in relationships

### ISSUE THREAD

**Issue by joelgrus** [FlatFilers/Guides#504]
on this page: https://flatfile.com/docs/blueprint/relationships

it says only `has-one` is supported

but on this page: https://flatfile.com/docs/blueprint/properties#reference

it says both `has-many` and `has-one` are supported

(also, it is unclear what 'has-many' would mean here)

**Comment by ashleygmulligan2** [comment]
I removed has-many but missed this, thank you
