### ISSUE TITLE
Creating a Workbook via API Doesn't add "Created By"

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#51]
When creating a workbook from the API there's no record in the UI of who created the workbook.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/110071258/234049975-3e22e65b-7c78-4f3a-8802-499d44d8c04c.png">

**Comment by ashleygmulligan2** [comment]
What would you expect it to say/be here?

**Comment by becca-weiss** [comment]
Whoever's API key it is but if this space list also gets added to on an embed, I would expect to see whatever end user triggered the space to get created

**Comment by ashleygmulligan2** [comment]
@lisamahapatra is on this one.

**Comment by lisamahapatra** [comment]
This will be addressed in the space list redesign, but not before soft launch. Def gonna address before GA

**Comment by ashleygmulligan2** [comment]
I'd like to move this issue to the X repo.
