### ISSUE TITLE
Docs for Auth endpoint for Account-level activities

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/Guides#518]
Examples of objects that should be retrievable at the account level, not just within a specific environment:

- Environments
- Events
- Users
- Guests
- Agents
- Spaces
- Workbooks
- Sheets
- Files
- Jobs

However, the [Docs](https://flatfile.com/docs/developer-tools/security/authentication) only show how to get environment-specific objects using the environment secret_key. We also need a way for developers to use their admin API key. This is useful when doing the following:

- Querying for all events across all environments, along with all users and guests, to build an audit log
- Determining how many Spaces exist and which ones exist in different environments
- Knowing which environments already have an agent deployed to that environment

**Comment by bigcountrycrane** [comment]
@ashleygmulligan2 Yes this would just be a documentation thing. We don't have anywhere that shows someone how to get their user API key (as opposed to the PK/SK that is environment specific)
