### ISSUE TITLE
Boolean Field Updates

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#532]
- Field does not current validate non-boolean values natively
- Field does not take commonly used values for boolean values and turn them into boolean values

_Originally posted by @ashleygmulligan2 in https://github.com/FlatFilers/Guides/issues/528#issuecomment-1591991816_
            

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_qh1zg)

**Comment by hansjhoffman** [comment]
@ashleygmulligan2 Per our conversation about Blueprints, this is likely to get resolved with future Blueprint updates or via field parser plugins. Consequently, should we close this issue since it's wrapped up in a much larger problem set?
