### ISSUE TITLE
curl example in docs does not match example from docs

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#56]
the curl example provided [here](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-workbook) does not match the example in the docs [here](https://flatfile.stoplight.io/docs/v10/branches/ashley-mulligan-sample-workbook/tjt005wdogklo-create-a-sample-workbook)

if someone is following along in the process and chooses to deploy from curl vs docs - they will have different fields.

**Comment by dboskovic** [comment]
Resolved by #66
