### ISSUE TITLE
Unable to successfully create a space in the UI

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#57]
after deploying [curl request](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-workbook) or [docs](https://flatfile.stoplight.io/docs/v10/branches/ashley-mulligan-sample-workbook/tjt005wdogklo-create-a-sample-workbook), when clicking the "Create new Space" button  and moving to the Space detail screen, the Create new Space button remains grayed out. The config dropdown remains empty throughout the process.

[Loom video](https://www.loom.com/share/93f24f5dfda643bcb9f5b253111d39e0)

**Comment by dboskovic** [comment]
While this isn't a bug (we actually aren't showing you how to setup space creation this early) we need to think about this "create space without space config" flow. cc @lisamahapatra 

There's a missing step 4 we're working on around deploying your space configuration for use with that button.

**Comment by ashleygmulligan2** [comment]
@lisamahapatra is working to make Space config not appear in the UI unless you have a Space Config in your Environment. Furthermore, we won't require a Space Config any longer to create a Space.

**Comment by ashleygmulligan2** [comment]
I'd like to move this Issue to the X repo.
