### ISSUE TITLE
Consistent Language: "the data" or "data" or "your data"

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#59]
I think we need to get consistent on the language we're using across the board here. When referring to data in the review table, in some places we say "the data" others we say "data" or "your data". This may seem like a stupid thing but fixing this will make us come off 10x more professionally.

**Comment by dboskovic** [comment]
_le dâta_ it is

**Comment by ashleygmulligan2** [comment]
Would love a PR to fix these as you find them, thanks!
