### ISSUE TITLE
Clicking on Copy icon to direct place in docs removes /docs/ from URL

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#591]
When you click the icon to direct link in the docs, whats copied to your clipboard removes /docs/ and then the link doesn't go anywhere...like this:
https://flatfile.com/developer-tools/environment#guest-authentication
instead of https://flatfile.com/docs/developer-tools/environment#guest-authentication

**Comment by ashleygmulligan2** [comment]
Can you send a link to the page this happened?

**Comment by becca-weiss** [comment]
@ashleygmulligan2 it was on the using environments page but looks like it's fixed now!

**Comment by madaley1** [comment]
Closing per prior comment that this issue has been resolved
