### ISSUE TITLE
API Key is listed in fullexample.ts in Replit

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#60]
There's an API key in the fullexample.ts in the Replit for people to use https://replit.com/@flatfile/get-started#fullexample.ts

**Comment by ashleygmulligan2** [comment]
Thank you, I am currently testing. This will go away soon.

**Comment by sunte2534** [comment]
> There's an API key in the fullexample.ts in the Replit for people to use https://replit.com/@flatfile/get-started#fullexample.ts

1. >
