### ISSUE TITLE
unable to successfully run cURL request

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#61]
receive the following error when trying to run the cURL request included [here](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-workbook):

`{
    "message": "Unexpected token } in JSON at position 298"
}`

**Comment by bigcountrycrane** [comment]
I have the same issue with the getting started script. I checked all of our brackets and they appeared to be correct, so maybe the JSON payload is incorrectly formed?

**Comment by elisadinsmore** [comment]
Also getting this, I am unable to deploy this cURL request

**Comment by dboskovic** [comment]
👀 Debugging this

**Comment by dboskovic** [comment]
Confirmed this is now resolved by #66
