### ISSUE TITLE
in cURL request example - do spaceId and environmentId need to be updated?

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#63]
will the user need to update the spaceId and environmentId in the example provided [here](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-workbook)?

`curl --request POST \
  --url https://platform.flatfile.com/api/v1/workbooks \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer <publishable key>' \
  --header 'Content-Type: application/json' \
  --data '{
  "name": "My Workbook",
  "spaceId": "us_sp_DrdXetPN",
  "environmentId": "us_env_hVXkXs0b",
  "sheets": [
    {
      "name": "My Sheet 1",
      "slug": "mysheet1",
      "fields": [
        {
          "key": "first_name",
          "type": "string",
          "label": "First Name",
        },
        {
          "key": "last_name",
          "type": "string",
          "label": "Last Name",
        },
        {
          "key": "email",
          "type": "string",
          "label": "Email",
        }
      ],
      "actions": [
        {
            "slug": "todogenerateJSON",
            "label": "todoGenerate JSON",
            "description": "todoGenerate a JSON file based off of the Data in this Sheet",
            "primary": true
        },
      ]
    }
  ],
}'
`

**Comment by elisadinsmore** [comment]
Another question related to this - how will customers know what spaceId to pass in if they don't have one yet?

**Comment by ashleygmulligan2** [comment]
Those should not be part of the request. Those should be gone now. Thank you
