### ISSUE TITLE
Example not acting as expected

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#65]
When using the Replit example in the perform and validate step, it's not clear to me if I have to take any additional action there. Do I update my API key and hit run and now my space updates with my data hooks? Do I need to re-deploy my space?

**Comment by dboskovic** [comment]
Can you re-read this now that it's been updated and see if the clarity problem still exists

**Comment by ashleygmulligan2** [comment]
Is this before you've done the transform step or after?

**Comment by ashleygmulligan2** [comment]
You're using a listener that is running locally so you don't need to deploy. It will immediately see changes once you start polling.

**Comment by ashleygmulligan2** [comment]
This should now be working. Please try again.
