### ISSUE TITLE
Confusing language about plug in example

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#69]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/110071258/234072267-73680262-5cf5-44cc-abbe-070ab2f8fb0b.png">
This is a little confusing, the title is "Using Action Plugins" but we're saying we're not going to use a plug in for the tutorial.

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/112
