### ISSUE TITLE
Not clear where we configured "submit action" earlier

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#70]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/110071258/234072657-34f89924-d513-40be-a7c8-59207df51cc2.png">
We're saying we configured this earlier but it wasn't mentioned about configuring it, just added to the example we deployed. Maybe clarify this or say something along the lines of "we'll configure the submit button you see in the workbook you already deployed"

**Comment by ashleygmulligan2** [comment]
thank you, fixed in this PR: https://github.com/FlatFilers/Guides/pull/109
