### ISSUE TITLE
Add Summary of CLI Commands 

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#704]
It would be good to have a page with a summary of the different CLI commands developers can use. We reference them when they're relevant in docs but developers looking for what's available won't easily be able to find them. 

Not sure if there are many more other than `npx flatfile deploy` and `npx flatfile develop` (possibly some other ones?) but it would be nice to include them all!

**Comment by ashleygmulligan2** [comment]
See if Merit's recent updates suffice!
