### ISSUE TITLE
Don't include link placeholders for packages that won't exist at launch

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#71]
I understand that there are plans to create packages that make interacting with the platform easier. However, right now we're positioning to the team that all of these packages will be available (and working, and tested) by May 1. 

Unless these packages are all getting built, for sure, this week, can we remove placeholders for the links?

<img width="751" alt="Screen Shot 2023-04-24 at 1 32 03 PM" src="https://user-images.githubusercontent.com/7946766/234073411-0eb04da8-ff21-41bc-8074-76b8cfd659ac.png">

<img width="738" alt="Screen Shot 2023-04-24 at 1 36 26 PM" src="https://user-images.githubusercontent.com/7946766/234073551-9045f043-8f9b-4d84-a395-185103f6fb1f.png">

<img width="742" alt="Screen Shot 2023-04-24 at 1 37 10 PM" src="https://user-images.githubusercontent.com/7946766/234073671-0d6fde19-69f3-4d2e-834f-1df94262d00a.png">

**Comment by ashleygmulligan2** [comment]
Thank you, we will update this closer to launch.

**Comment by ashleygmulligan2** [comment]
We now have placeholders for these. Thank you
