### ISSUE TITLE
What's an import space?

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#73]
What's an import space? Should this just say space? Since you can deploy a workbook without a space should this say something else? 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/110071258/234074741-ac7414bf-561e-476a-9ea3-56f1af83473a.png">

**Comment by ashleygmulligan2** [comment]
Thank you, updated in this PR: https://github.com/FlatFilers/Guides/pull/106
