### ISSUE TITLE
Environment types on page don't match API docs

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#74]
Environment guide page: https://flatfileinc.mintlify.app/security/authentication#testing-and-development

The docs present environments as a "Type" that has values of either "Live" or "Test"

<img width="746" alt="Screen Shot 2023-04-24 at 1 39 53 PM" src="https://user-images.githubusercontent.com/7946766/234074485-32e84599-c32e-4949-b36d-872691e82ff0.png">

But the /environments endpoints treat "Type" differently. It's simply a boolean toggle on "isProd"

<img width="281" alt="Screen Shot 2023-04-24 at 1 41 27 PM" src="https://user-images.githubusercontent.com/7946766/234074578-8696aafe-1420-4455-bd55-cd2f6973ca33.png">

**Comment by ashleygmulligan2** [comment]
Ryan is working on this for us

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/130
