### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by GabDesilets** [FlatFilers/Guides#740]
Path: /quickstart/create-your-workbook
The send request button doesn't work even with all the fields in the body filled.
The call return a 200 with a response like this:
```
{"highlightedJson":null}
````

The body looked like:
```
{
  "method": "post",
  "url": "https://platform.flatfile.com/api/v1/workbooks",
  "body": {
    "name": "TestWorkbook",
    "sheets": [
      {
        "name": "sheet1",
        "slug": "s1",
        "fields": [
          {
            "key": "fname",
            "type": "string",
            "label": "First Name"
          },
          {
            "key": "email",
            "type": "string",
            "label": "Email"
          }
        ]
      }
    ],
    "actions": [
      {
        "operation": "submitAction",
        "primary": true,
        "mode": "foreground",
        "label": "Send it",
        "description": "send data to webhook"
      }
    ]
  },
  "headers": {
    "Accept": "application/json",
    "Content-type": "application/json",
    "Authorization": "Bearer <Redacted>"
  }
}
```
The curl command works fine and the only difference i could see is that the curl include `"labels": ["simple-demo"],` at the root with name for the workbook.
![image](https://github.com/FlatFilers/Guides/assets/3750714/3ba3e82a-9661-4bc3-a546-676d4c6898f3)

**Comment by madaley1** [comment]
This looks a lot like this issue:
https://github.com/FlatFilers/Guides/issues/838

@GabDesilets could  you confirm whether it's been fixed for you or not?

**Comment by GabDesilets** [comment]
i don't know i haven't re-use the documentation or flatfile, pretty sure we can close this
