### ISSUE TITLE
Clarity on "allow_custom" setting

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#748]
We have an `allow_custom` [config property for enum](https://flatfile.com/docs/blueprint/field-types#enum) values right now, but what it does is allow end users to "leave values as is" on the mapping screen and edit them later. It does _not_ turn these into accepted enum values, so they will still show an error. 

We should provide clarity around this property in the docs because the way it is currently named, it appears to allow end users to add new valid enum options.

**Comment by ashleygmulligan2** [comment]
fixed in: https://github.com/FlatFilers/Guides/pull/757
