### ISSUE TITLE
Does the "development" environment use credits?

### ISSUE THREAD

**Issue by becca-weiss** [FlatFilers/Guides#75]
This may be more of a @dboskovic question but if the answer is "yes" we should clarify in docs. Will customers use real credits when using the "development" environment? 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/110071258/234075319-80ba6784-1119-4c84-a405-8f8cdd208f41.png">

**Comment by dboskovic** [comment]
This is a good question. The "right" answer is no. But we need to introduce ways to prevent abuse of this.

**Comment by ashleygmulligan2** [comment]
Added a note to Auth page
