### ISSUE TITLE
Clarify Flatfile concepts and distinguish from general terminology

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#76]
Example from Authentication page: https://flatfileinc.mintlify.app/security/authentication

Here, we describe a "Space" as an "import space":

<img width="668" alt="Screen Shot 2023-04-24 at 1 45 24 PM" src="https://user-images.githubusercontent.com/7946766/234075439-0f9ad7ec-9b4e-478f-8b75-8c0a55fd04f9.png">

Later in the guide, we use "space" in an entirely different context: 
<img width="728" alt="Screen Shot 2023-04-24 at 1 47 00 PM" src="https://user-images.githubusercontent.com/7946766/234075743-833caf93-a761-4257-8f77-fe807daefb1d.png">

**Comment by bigcountrycrane** [comment]
Related to @becca-weiss note in https://github.com/FlatFilers/Guides/issues/73

**Comment by ashleygmulligan2** [comment]
Thank you, I agree. Fixed in this PR: https://github.com/FlatFilers/Guides/pull/173
