### ISSUE TITLE
Wrong/missing links on Using Actions Guide page

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#773]
Path: [/guides/actions]

Link to the example in Usage section for Sheet-mounted actions leads to a 404 not found  
https://flatfile.com/docs/guides/actions#usage-2

Link to the example in Usage section for File actions also leads to a 404 not found 
https://flatfile.com/docs/guides/actions#usage-3

Both links are at the bottom of the corresponding Usage section

**Comment by ashleygmulligan2** [comment]
fixed
