### ISSUE TITLE
Incorrect/missing links for example projects in Actions

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#777]
Path: /concepts/actions 

Link: https://flatfile.com/docs/concepts/actions#example-projects

Both typescript and javascript links lead to a 404 not found page

Note from Ashley: For all of our Guides, at the end, we link to the repos. Can you check that all of these work properly?

**Comment by madaley1** [comment]
Noting that the typescript and javascript links seem to work now, so they may have been fixed before now. I'll check out the rest of the guides rq to ensure all of them are correct.
