### ISSUE TITLE
Multi-Space Guest description

### ISSUE THREAD

**Issue by bigcountrycrane** [FlatFilers/Guides#78]
Not sure if this is true; I think multi-Space Guests can select other spaces from a dropdown, but they can't go back to the dashboard and don't have a login. Does this assume that this is a feature to be built this week?

<img width="747" alt="Screen Shot 2023-04-24 at 1 49 44 PM" src="https://user-images.githubusercontent.com/7946766/234076445-1423e3a1-a914-40e4-a271-4e936d4c3aea.png">

**Comment by ashleygmulligan2** [comment]
Thank you, no it doesn't assume that. I thought they had a landing page to see all of their Spaces but that's still in progress so I will update

**Comment by ashleygmulligan2** [comment]
Fixed in this PR: https://github.com/FlatFilers/Guides/pull/98
