### ISSUE TITLE
Capitalization of Flatfile Terminology

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#82]
Should "Workbook" be consistently capitalized? I'm seeing it capitalized in some places but not in others. I think it should at least be capitalized [here](https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#create-a-workbook) in the title of "Create a Workbook."

**Comment by dboskovic** [comment]
Hmmmm that's a good question. We should probably have a way of referring to glossary concepts consistently.

**Comment by ashleygmulligan2** [comment]
I was feeling like it was obnoxious to capitalize terms in every sentence. I'd love for our pattern to be to always link to learn more about a concept once in a doc, not more than once. And I'm leaning towards not using uppercase at all otherwise every other words is capitalized.

**Comment by ashleygmulligan2** [comment]
We've made a decision to lowercase for terms
