### ISSUE TITLE
Video in Meet the Workbook Overview not working

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#83]
Video loads nothing.

<img width="743" alt="Screen Shot 2023-04-24 at 1 24 55 PM" src="https://user-images.githubusercontent.com/95828208/234083597-f533eddc-df85-4ac6-931c-58bb55dab70e.png">

**Comment by ashleygmulligan2** [comment]
I was in the process of merging to a remote host, thanks! Fixed now.
