### ISSUE TITLE
"Create your workbook" helper on docs not working

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#838]
The "Create a workbook" option on docs here: https://flatfile.com/docs/quickstart/create-your-workbook does not appear to actually be working. I'm passing in a valid secret key copied directly from my dashboard, that works in other places, and getting "no response received" when trying to create a workbook. 

Nothing appears in my dashboard after making this change, either. 

![Image](https://github.com/orgs/FlatFilers/projects/6/assets/106406547/af0ed649-cc8c-41d7-a78a-612abf7efd30)

**Comment by madaley1** [comment]
Created a PR for this, the only way I could get a response was by adding a Labels array to the top level of the record, which was in the cURL command but not in the request sent by the docs. Adding it seems to have fixed it.
