### ISSUE TITLE
.env file in example photo

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#85]
Super nit-picky, but aren't we moving to the .flatfilerc file rather than .env? I noticed this picture on the meet-the-workbook page includes a .env file 

![image](https://user-images.githubusercontent.com/106406547/234087635-96dbac03-0984-4e47-a682-11e7724359f4.png)

Please ignore if this is a non-issue :)

**Comment by ashleygmulligan2** [comment]
Thank you, yes will fix
