### ISSUE TITLE
Issue on docs - Add Data Transformation

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#86]
Path: /quickstart/add-data-transformation

`Transform and validate data` section

updated verbiage:

> Begin the process of validating and transforming data in Flatfile by implementing a basic event handler.

> After creating a workbook with a simple schema in the previous step, follow these next steps to prepare for validation and transformation:

> -  Manually add a few sample records to your workbook.
> - Try uploading a CSV file into your workbook to see how it handles the data.

- Do we want to provide a sample csv file here?

> Every action you perform in Flatfile triggers an event. You can listen to these events to perform various tasks such as validating records and sending data to your API.

`Setting up a listener` section

updated verbiage:

> Get your Secret Key from your [Developer Dashboard](https://platform.flatfile.com/developers)

When I hit run in Repl.it - what is the expected behavior?  I get the following in the console and the play button turns to stop.  

<img width="661" alt="Screen Shot 2023-04-24 at 12 57 15 PM" src="https://user-images.githubusercontent.com/110066636/234090371-cbc4633f-7b0e-4946-a8b8-f41655eb61cb.png">

- What timezone is represented in the screenshot?

`Subscribing to Events` section

updated verbiage:

> After clicking the Run button in the pre-configured Repl.it, you will see a "Listening for Events" message in the console. To test the event listener, return to your workbook page and make a few changes to your records in the Flatfile workbook. You should see events and logs appearing in your console.

- Can we provide examples based on common changes?  Explanations of sheet: validated, records: created, and records: updated?

`Subscribing to Events` section

updated verbiage:

> In this tutorial, we will transform data as it is added or modified in the sheet using Flatfile's transformation and validation plugins. There are various open source validation plugins available that you can explore, such as:

- do we want to add Flatfile specific language here - ex: added (records:created) or modified (records:updated)

'Using a plugin to transform data' section

- What is the call to action for the user here?  Are we expecting them to add this example code to the forked replit and run it?

'Adding your first validation' section

- What is the call to action for the user here?  Are we expecting them to add this example code to the forked replit and run it?

'Recap & Next Steps' section

> After following the previous steps, you should now have a listener running on your local machine that responds to any changes made to your Workbook's records.

> Moving forward, the next step is to incorporate an action that will allow you to submit the data from your Sheet to your API.

- should they also have working transformations in their workbook?

**Comment by ashleygmulligan2** [comment]
Mind making a PR for this?
