### ISSUE TITLE
Replit Starter Example - API Key

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/Guides#88]
In the Replit starter example, on the [index.ts file](https://replit.com/@flatfile/get-started#index.ts) - "YOUR API KEY" is referenced.  What is this equal to in the Flatfile UI? Publishable Key? Secret Key? Something else?

**Comment by ashleygmulligan2** [comment]
Secret key should be used here. We will update that terminology for clarity

**Comment by ashleygmulligan2** [comment]
Please check now
