### ISSUE TITLE
Clarification on API Key needed

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#89]
The listener example here: https://replit.com/@flatfile/get-started#index.ts asks for your API key, and mentions they can get this at platform.flatfile.com 

Is this the API token under settings > Personal Tokens, the publishable key, the secret key, or a bearer token? More info or instructions on how to get this would be great!

**Comment by elisadinsmore** [comment]
From the fullexample.ts file, it looks like this is the secret key - would be good to call out.

**Comment by colinfrederickson** [comment]
@elisadinsmore - might have been resolved by https://github.com/FlatFilers/Guides/issues/88

**Comment by ashleygmulligan2** [comment]
Thank you, I should always be linking to platform.flatfile.com/developers from now on. New people shouldn't know about client id and it should be removed from the UI soon as well.
