### ISSUE TITLE
Docs Feedback - faulty link 

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#91]
**Where:** https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#using-schemas 

**What:** when clicking on blueprint converter plugins hyperlink, it goes to a page with error: 

<img width="786" alt="Screenshot 2023-04-24 at 1 58 34 PM" src="https://user-images.githubusercontent.com/114111637/234090791-1e7ade5a-0e88-41be-a052-198af0f94648.png">
<img width="1027" alt="Screenshot 2023-04-24 at 1 58 41 PM" src="https://user-images.githubusercontent.com/114111637/234090809-0619d51b-3ee3-44a2-bbe9-d72985e419ea.png">

**Comment by ashleygmulligan2** [comment]
Thank you, this page is still being built. Will mark as resolved once it's published.

**Comment by ashleygmulligan2** [comment]
This is now complete
