### ISSUE TITLE
Docs Feedback - wording, step 1 quickstart

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#92]
**Where:** https://flatfileinc.mintlify.app/quickstart/meet-the-workbook#recap-and-next-steps

**What:** right now we say `"Now that you have a workbook in your Dashboard and know how to use schemas in Flatfile, you can actually stop here if this solves your use case."` -
I am not sure this is the best way to approach this, don't we want the user to continue exploring the possibilities of Flatfile? At this point, the only thing they did was create a simple schema. They did not do any validations, they did not think through what happens next and how to get the data out, and we are gently "kicking them out". I am not familiar with a use case where that would be enough. 

Our [current SDK docs have this phrased better](https://docs.flatfile.com/docs/get-started/quickstart/#try-it-out), could we adapt something similar?

> You're now ready to start importing data with Flatfile! _Insert here steps they can take to see the workbook and go through a test import._ After you finish importing, you should see the data appear in the Workbook sheet. Next, let's take things a step further and learn how to respond to record events with transformations and validations.

**Comment by dboskovic** [comment]
For terminology feedback, would you be able to actually pull request this?

**Comment by ashleygmulligan2** [comment]
I have a PR if you want to review: https://github.com/FlatFilers/Guides/pull/95
