### ISSUE TITLE
Type errors when copying examples

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#94]
When I copy the first example validation under "Using a plugin to transform data" and paste it into repl.it, I get type errors. 

```
import { recordHook } from '@flatfile/plugin-record-hook'

export default function(listener) {
  listener.use(
    recordHook('contacts', (record) => {
      record.set('firstName', record.get('firstName').toUpperCase())
      return record
    })
  )
}
```

![image](https://user-images.githubusercontent.com/106406547/234094241-be92a32f-4d52-44af-9b91-c9612a90ea55.png)

![image](https://user-images.githubusercontent.com/106406547/234094293-47f3ae68-9407-4a85-b119-958dd337e0f5.png)

![image](https://user-images.githubusercontent.com/106406547/234094661-671862f5-e044-43c3-b9e4-218a65267619.png)

Also seeing these in VSCode

**Comment by ashleygmulligan2** [comment]
Thank you, this is in progress as we speak. I'll let you know when complete.

**Comment by ashleygmulligan2** [comment]
Please try replit, will update the copy/paste functionality later

**Comment by dboskovic** [comment]
This is now resolved! Try again.
