### ISSUE TITLE
Messy example tabs of handling-data

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#967]
The tabs of these two examples in handling-data have variable definitions but those should be a part of the code text box while the tab should have the file name (if we're keeping it consistent with other example modals).

https://flatfile.com/docs/guides/handling-data#example-4
https://flatfile.com/docs/guides/handling-data#example-5

<img width="741" alt="Screen Shot 2023-11-30 at 5 01 49 PM" src="https://github.com/FlatFilers/Guides/assets/95828208/ab276dba-dcee-49f1-9cee-2e8fdae46339">
<img width="730" alt="Screen Shot 2023-11-30 at 5 02 02 PM" src="https://github.com/FlatFilers/Guides/assets/95828208/3fb74a68-900e-4b03-ba8f-452497274061">

**Comment by ashleygmulligan2** [comment]
fixed
