### ISSUE TITLE
Contradictory phrasing

### ISSUE THREAD

**Issue by elisadinsmore** [FlatFilers/Guides#97]
Under "Using a plugin to transform data", we say the following transformation will take the first name and make it lowercase, but the example has a .toUpperCase() method. 

https://flatfileinc.mintlify.app/quickstart/add-data-transformation#using-a-plugin-to-transform-data

**Comment by ashleygmulligan2** [comment]
Solved in this PR: https://github.com/FlatFilers/Guides/pull/95 - thank you
