### ISSUE TITLE
Deploying to Flatfile docs confusing to customers

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#980]
Path: /developer-tools/deploying
When customers visit https://flatfile.com/docs/developer-tools/deploying to learn about deploying Flatfile, the first section they see is "Hosting in your own Cloud" section which throws them off and gives them the impression that this is the primary way we recommend they implement. This causes a lot of confusion and questions in support. Could we consider moving that section to the bottom of the page so that Hosting on the Flatfile platform is the first thing they see instead? 
Also, what is the use case for hosting in your own cloud? Maybe we need to remove it or reword in some way? I am not clear on when and why someone might choose that path, so unsure if we need this

**Comment by ashleygmulligan2** [comment]
fixed
