### ISSUE TITLE
"Latest" option in version dropdown can't be seen

### ISSUE THREAD

**Issue by syshinnn** [FlatFilers/Guides#985]
The font of "latest" is white so it blends in with the background. You can see it if you double click to highlight it.

<img width="301" alt="Screen Shot 2023-12-19 at 1 59 13 PM" src="https://github.com/FlatFilers/Guides/assets/95828208/788b77ae-6fb4-4acc-a821-8ea269292303">
<img width="304" alt="Screen Shot 2023-12-19 at 2 03 40 PM" src="https://github.com/FlatFilers/Guides/assets/95828208/c9fd3c47-0f78-4205-ad43-b3ec4d12b3e5">

**Comment by ashleygmulligan2** [comment]
fixed
