### ISSUE TITLE
When hovering over bolded concepts in light mode, the hint message is just a black box

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#987]
Path: /guides/use-cases/collaborate
Example: https://flatfile.com/docs/guides/use-cases/collaborate

When I hover over bolded concepts in light mode, the hint is just a black box: 

<img width="786" alt="Screenshot 2023-12-19 at 2 17 34 PM" src="https://github.com/FlatFilers/Guides/assets/114111637/04932d3b-f729-4ab3-83ed-c541e647c1bd">

**Comment by ashleygmulligan2** [comment]
fixed
