### ISSUE TITLE
Drop shadow

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#988]
Path: /guides/use-cases/embedding/react/guide

Whenever there are multiple link blocks on the page, the shadow of the last block is always thinner/cut off - is this by design? 

<img width="774" alt="Screenshot 2023-12-19 at 2 42 29 PM" src="https://github.com/FlatFilers/Guides/assets/114111637/1e5cfe81-1fed-4fe2-97ae-1167d3a37313">

**Comment by ashleygmulligan2** [comment]
ah yea, it's getting cut off by the outer container. i cannot fix
