### ISSUE TITLE
Hint box fortmatting

### ISSUE THREAD

**Issue by agilbaugh** [FlatFilers/Guides#989]
Link:
https://flatfile.com/docs/developer-tools/developing/check-for-agents 

The hint box when you click on "i" looks bit and it's not clear - is there more data missing there that I'm not seeing? Or is it just extra blank space? 

<img width="815" alt="Screenshot 2023-12-19 at 2 59 09 PM" src="https://github.com/FlatFilers/Guides/assets/114111637/6f2e2b8e-6ef0-41a0-aaf4-4074d522b59b">

**Comment by elisadinsmore** [comment]
It looks like some of this has been fixed, but the styling is still wonky on light mode and some words can't be read: 
![image](https://github.com/FlatFilers/Guides/assets/106406547/541a5474-af13-4028-a511-c6f61b0de352)

**Comment by ashleygmulligan2** [comment]
This page is gone
